online_shop/cart/urls.py
from django.urls import path

from . import views

app_name = "cart"

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove')
]

online_shop/online_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from shop.views import page_not_found

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('coupons/', include('coupons.urls', namespace='coupons')),
    path('users/', include('users.urls', namespace='users')),
    path('', include('shop.urls', namespace='shop')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

handler404 = page_not_found

admin.site.site_header = "Панель администрирования онлайн-магазина"
admin.site.index_title = "Выберите объект для администрирования"

online_shop/shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.ProductList.as_view(), name='product_list'),
    path('<slug:category_slug>/', views.ProductList.as_view(), name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.ProductDetail.as_view(), name='product_detail'),
]

online_shop/users/urls.py
from django.contrib.auth.views import LogoutView, PasswordChangeView, PasswordChangeDoneView, PasswordResetView, \
    PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path, reverse_lazy

from . import views

app_name = 'users'

urlpatterns = [
    path('login/', views.LoginUser.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('password-change/', views.UserPasswordChange.as_view(), name='password_change'),
    path('password-change/done/', PasswordChangeDoneView.as_view(template_name='users/password_change_done.html'),
                                                                 name='password_change_done'),
    path('password-reset/', PasswordResetView.as_view(template_name='users/password_reset_form.html',
                                                      email_template_name='users/password_reset_email.html',
                                                      success_url=reverse_lazy("users:password_reset_done")),
                                                      name='password_reset'),
    path('password-reset/done/', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
                                                               name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html',
                                                                              success_url=reverse_lazy('users:password_reset_complete')),
                                                                              name='password_reset_confirm'),
    path('password-reset/complete/', PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
                                                                       name='password_reset_complete'),

    path('register/', views.RegisterUser.as_view(), name='register'),
    path('profile/', views.ProfileUser.as_view(), name='profile'),
]

online_shop/shop/models.py
from django.db import models
from django.urls import reverse


# Модель Категории
class Category(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True)

    class Meta:
        ordering = ['name']
        indexes = [models.Index(fields=['name'])]
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category', args=[self.slug])


# Модель Продукт (товар)
class Product(models.Model):
    category = models.ForeignKey(Category,
                                 related_name='products',
                                 on_delete=models.CASCADE)

    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['name']
        indexes = [
            models.Index(fields=['id', 'slug']),
            models.Index(fields=['name']),
            models.Index(fields=['-created'])
        ]

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id, self.slug])

online_shop/shop/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, DetailView

from cart.forms import CartAddProductForm
from .models import Category, Product


# Каталог товаров
class ProductList(ListView):
    template_name = 'shop/product/list.html'
    context_object_name = 'products'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        # Если передан слаг, по нему из БД получаем категорию и сохраняем в контекст
        if self.kwargs.get('category_slug'):
            context['category'] = get_object_or_404(Category, slug=self.kwargs.get('category_slug'))
        else:
            context['category'] = None
        return context

    def get_queryset(self):
        # Если в запросе есть слаг категории, то выдаем товары этой категории
        if self.kwargs.get('category_slug'):
            category = get_object_or_404(Category, slug=self.kwargs.get('category_slug'))
            return Product.objects.filter(available=True, category=category)
        return Product.objects.filter(available=True)


# Карточка товара
class ProductDetail(DetailView):
    template_name = 'shop/product/detail.html'
    context_object_name = 'product'

    extra_context = {
        'cart_product_form': CartAddProductForm(),
    }

    def get_object(self, queryset=None):
        id = self.kwargs.get('id')
        slug = self.kwargs.get('slug')
        return get_object_or_404(Product,
                                 id=id,
                                 slug=slug,
                                 available=True)


# Обработка ошибки 404
def page_not_found(request, exception):
    return render(request,
                  'shop/page_not_found.html')

online_shop/shop/templates/shop/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{% block title %}My shop{% endblock %}</title>
    <link href="{% static 'css/base.css' %}" rel="stylesheet">
</head>

<body>
    <div class="header-block">
        <div id="header">
            <a href="/" class="logo">Магазин LC</a>
        </div>
        <div class="auth-block">
            {% if user.is_authenticated %}
                <a href="{% url 'users:profile' %}">{{ user.username }}</a><span> | </span><form method='post' action="{% url 'users:logout' %}">{% csrf_token %}<button type="submit">Выйти</button></form>
            {% else %}
                <a href="{% url 'users:login' %}">Войти</a> |
                <a href="{% url 'users:register' %}">Регистрация</a>
            {% endif %}
        </div>
    </div>
    <div id="subheader">
        <div class="cart">
            {% with total_items=cart|length %}
                {% if total_items > 1 %}
                    Ваша корзина:
                    <a href="{% url 'cart:cart_detail' %}">
                        {{ total_items }}
                        товаров на сумму {{ cart.get_total_price }}
                    </a>
                {% elif total_items == 1 %}
                    Ваша корзина:
                    <a href="{% url 'cart:cart_detail' %}">
                        {{ total_items }}
                        товар на сумму {{ cart.get_total_price }}
                {% elif not order %}Ваша корзина пуста
                {% endif %}
            {% endwith %}
        </div>
    </div>
    <div id="content">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

online_shop/shop/templates/shop/page_not_found.html
{% extends 'shop/base.html' %}

{% block title %}Страница не найдена{% endblock %}

{% block content %}
<h1>Ошибка 404: страница не найдена</h1>
<a href="{% url 'shop:product_list' %}">Перейти в каталог</a>
{% endblock %}